In [2]:
import numpy as np

In [153]:
n_terms, n_cats = 10000, 30
X = abs(np.random.randn(n_terms,n_cats))
X = X / X.sum(axis=1).sum(axis=0)

c = abs(np.random.randn(n_cats))
c = c / c.sum()

t = X.sum(axis=1)

In [115]:
n_terms, n_cats = 3, 3
X = np.array([[0.5,0.1,0.1],[0.1,0.6,0.05],[0.1,0.05,0.5]])

c = abs(np.random.randn(n_cats))
c = c / c.sum()

t = X.sum(axis=1)

In [116]:
ig = np.log((X / np.outer(t,c)))*X

In [117]:
(X.T / t).T

array([[ 0.71428571,  0.14285714,  0.14285714],
       [ 0.13333333,  0.8       ,  0.06666667],
       [ 0.15384615,  0.07692308,  0.76923077]])

In [154]:
ig = np.log( ((X.T / t).T)**(X*c) ) + np.log( ( ((1-X).T / (1-t)).T)**(c - X*c))

In [156]:
np.argsort( np.sort(-ig, axis=1)[:,0] )[:10]

array([6899, 7002,  187,    1, 3091, 5192, 6936, 4093, 8491, 9664])

In [123]:
np.argsort(np.sort(-ig, axis=1)[:,0])

array([1787, 6696, 2063, ..., 3472, 6632, 8394])

In [7]:
ig.sort(axis=1).shape

AttributeError: 'NoneType' object has no attribute 'shape'

In [8]:
np.sort([1,2,3,5,-1,-2,10])

array([-2, -1,  1,  2,  3,  5, 10])

In [9]:
a = np.arrayt

AttributeError: module 'numpy' has no attribute 'arrayt'

In [10]:
a.shape

NameError: name 'a' is not defined

In [11]:
t[-5:]

array([  8.18323533e-05,   8.56833390e-05,   6.51953809e-05,
         1.14838885e-04,   8.38389105e-05])

In [12]:
import nltk

In [13]:
fd = nltk.FreqDist()

In [124]:
fd += nltk.FreqDist(["hallo","paul","hallo","paul","hund"])
a = np.array(list(fd.keys()))

In [136]:
np.array([
            [i+4*j for i in range(4)] 
              for j in range(3)
        ])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
list(fd)

['hallo', 'hund', 'paul']

In [21]:
import pydoc

In [28]:
pydoc.help(nltk.FreqDist)

Help on class FreqDist in module nltk.probability:

class FreqDist(collections.Counter)
 |  A frequency distribution for the outcomes of an experiment.  A
 |  frequency distribution records the number of times each outcome of
 |  an experiment has occurred.  For example, a frequency distribution
 |  could be used to record the frequency of each word type in a
 |  document.  Formally, a frequency distribution can be defined as a
 |  function mapping from each sample to the number of times that
 |  sample occurred as an outcome.
 |  
 |  Frequency distributions are generally constructed by running a
 |  number of experiments, and incrementing the count for a sample
 |  every time it is an outcome of an experiment.  For example, the
 |  following code will produce a frequency distribution that encodes
 |  how often each word occurs in a text:
 |  
 |      >>> from nltk.tokenize import word_tokenize
 |      >>> from nltk.probability import FreqDist
 |      >>> sent = 'This is an example se

In [35]:
fd.B()

3

In [71]:
np.array([[1,1],[1,1]]) / np.array([2,1])

array([[ 0.5,  1. ],
       [ 0.5,  1. ]])

In [73]:
np.array([[1,1],[1,1]]) * np.array([[1,0],[1,2]])

array([[1, 0],
       [1, 2]])

In [64]:
np.allclose(np.diag(t**(-1)).dot(X),(X.T / t).T)

True

In [58]:
(t.reshape(1,10000)**-1).shape

(1, 10000)

In [65]:
import time

In [150]:
ta = time.time()
for i in range(100000):
    i**2
for i in range(100000):
    i+2
tb = time.time()
for i in range(100000):
    i**2
    i+2
tc = time.time()

In [151]:
tb - ta

0.11224699020385742

In [152]:
tc - tb

0.08395004272460938

In [109]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [110]:
Out[109]**(np.eye(3))

array([[ 0.,  1.,  1.],
       [ 1.,  4.,  1.],
       [ 1.,  1.,  8.]])

In [138]:
set(a)

{'hallo', 'hund', 'paul'}

In [149]:
np.arange(9)[[1,2,2,3,3]]

array([1, 2, 2, 3, 3])